// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlzGeo.Api.Models;

#nullable disable

namespace PlzGeo.Api.Migrations
{
    [DbContext(typeof(PlzGisContext))]
    [Migration("20260829140451_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "tiger", "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "topology", "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlzGeo.Api.Models.GroupLegendItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.HasKey("Id")
                        .HasName("group_legend_items_pkey");

                    b.HasIndex("VisualizationId");

                    b.ToTable("group_legend_items", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.HeatmapLegendItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<decimal>("FromValue")
                        .HasColumnType("numeric")
                        .HasColumnName("from_value");

                    b.Property<decimal>("ToValue")
                        .HasColumnType("numeric")
                        .HasColumnName("to_value");

                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.HasKey("Id")
                        .HasName("heatmap_legend_items_pkey");

                    b.HasIndex("VisualizationId");

                    b.ToTable("heatmap_legend_items", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Plz5De", b =>
                {
                    b.Property<int>("OgcFid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ogc_fid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OgcFid"));

                    b.Property<string>("AdminLeve")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("admin_leve");

                    b.Property<string>("BorderTyp")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("border_typ");

                    b.Property<string>("Boundary")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("boundary");

                    b.Property<decimal?>("Fid")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20)")
                        .HasColumnName("fid");

                    b.Property<double?>("OsmId")
                        .HasColumnType("double precision")
                        .HasColumnName("osm_id");

                    b.Property<string>("Plz")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("plz");

                    b.Property<int?>("PostalAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("postal_area_id");

                    b.Property<string>("Type")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("type");

                    b.Property<MultiPolygon>("WkbGeometry")
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("wkb_geometry");

                    b.HasKey("OgcFid")
                        .HasName("plz_5_de_pk");

                    b.HasIndex("PostalAreaId");

                    b.HasIndex(new[] { "WkbGeometry" }, "plz_5_de_wkb_geometry_geom_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "WkbGeometry" }, "plz_5_de_wkb_geometry_geom_idx"), "gist");

                    b.ToTable("plz_5_de", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.PostalArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id")
                        .HasName("postal_areas_pkey");

                    b.HasIndex(new[] { "PostalCode" }, "postal_areas_plz_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PostalCode" }, "uq_postal_areas_plz")
                        .IsUnique();

                    b.ToTable("postal_areas", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("visualizations_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("visualizations", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.VisualizationValue", b =>
                {
                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.Property<int>("PostalAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("postal_area_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("VisualizationId", "PostalAreaId")
                        .HasName("visualization_values_pkey");

                    b.HasIndex("PostalAreaId");

                    b.HasIndex(new[] { "VisualizationId", "PostalAreaId" }, "uq_visualization_postal_area")
                        .IsUnique();

                    b.ToTable("visualization_values", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.GroupLegendItem", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("GroupLegendItems")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_legend_items_visualization_id_fkey");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.HeatmapLegendItem", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("HeatmapLegendItems")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("heatmap_legend_items_visualization_id_fkey");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Plz5De", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.PostalArea", "PostalArea")
                        .WithMany("Plz5Des")
                        .HasForeignKey("PostalAreaId")
                        .HasConstraintName("fk_plz_postal_area");

                    b.Navigation("PostalArea");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.User", "User")
                        .WithMany("Visualizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visualizations_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.VisualizationValue", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.PostalArea", "PostalArea")
                        .WithMany("VisualizationValues")
                        .HasForeignKey("PostalAreaId")
                        .IsRequired()
                        .HasConstraintName("visualization_values_postal_area_id_fkey");

                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("VisualizationValues")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visualization_values_visualization_id_fkey");

                    b.Navigation("PostalArea");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.PostalArea", b =>
                {
                    b.Navigation("Plz5Des");

                    b.Navigation("VisualizationValues");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.User", b =>
                {
                    b.Navigation("Visualizations");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.Navigation("GroupLegendItems");

                    b.Navigation("HeatmapLegendItems");

                    b.Navigation("VisualizationValues");
                });
#pragma warning restore 612, 618
        }
    }
}
