// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlzGeo.Api.Models;

#nullable disable

namespace PlzGeo.Api.Migrations
{
    [DbContext(typeof(PlzGisContext))]
    partial class PlzGisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "tiger", "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "topology", "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.GroupLegendItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.HasKey("Id")
                        .HasName("group_legend_items_pkey");

                    b.HasIndex("VisualizationId");

                    b.ToTable("group_legend_items", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.HeatmapLegendItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<decimal>("FromValue")
                        .HasColumnType("numeric")
                        .HasColumnName("from_value");

                    b.Property<decimal>("ToValue")
                        .HasColumnType("numeric")
                        .HasColumnName("to_value");

                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.HasKey("Id")
                        .HasName("heatmap_legend_items_pkey");

                    b.HasIndex("VisualizationId");

                    b.ToTable("heatmap_legend_items", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Plz5De", b =>
                {
                    b.Property<int>("OgcFid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ogc_fid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OgcFid"));

                    b.Property<string>("AdminLeve")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("admin_leve");

                    b.Property<string>("BorderTyp")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("border_typ");

                    b.Property<string>("Boundary")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("boundary");

                    b.Property<decimal?>("Fid")
                        .HasPrecision(20)
                        .HasColumnType("numeric(20)")
                        .HasColumnName("fid");

                    b.Property<double?>("OsmId")
                        .HasColumnType("double precision")
                        .HasColumnName("osm_id");

                    b.Property<string>("Plz")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("plz");

                    b.Property<int?>("PostalAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("postal_area_id");

                    b.Property<string>("Type")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("type");

                    b.Property<MultiPolygon>("WkbGeometry")
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("wkb_geometry");

                    b.HasKey("OgcFid")
                        .HasName("plz_5_de_pk");

                    b.HasIndex("PostalAreaId");

                    b.HasIndex(new[] { "WkbGeometry" }, "plz_5_de_wkb_geometry_geom_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "WkbGeometry" }, "plz_5_de_wkb_geometry_geom_idx"), "gist");

                    b.ToTable("plz_5_de", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.PostalArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id")
                        .HasName("postal_areas_pkey");

                    b.HasIndex(new[] { "PostalCode" }, "postal_areas_plz_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PostalCode" }, "uq_postal_areas_plz")
                        .IsUnique();

                    b.ToTable("postal_areas", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("visualizations_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("visualizations", (string)null);
                });

            modelBuilder.Entity("PlzGeo.Api.Models.VisualizationValue", b =>
                {
                    b.Property<Guid>("VisualizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("visualization_id");

                    b.Property<int>("PostalAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("postal_area_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("VisualizationId", "PostalAreaId")
                        .HasName("visualization_values_pkey");

                    b.HasIndex("PostalAreaId");

                    b.HasIndex(new[] { "VisualizationId", "PostalAreaId" }, "uq_visualization_postal_area")
                        .IsUnique();

                    b.ToTable("visualization_values", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlzGeo.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlzGeo.Api.Models.GroupLegendItem", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("GroupLegendItems")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_legend_items_visualization_id_fkey");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.HeatmapLegendItem", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("HeatmapLegendItems")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("heatmap_legend_items_visualization_id_fkey");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Plz5De", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.PostalArea", "PostalArea")
                        .WithMany("Plz5Des")
                        .HasForeignKey("PostalAreaId")
                        .HasConstraintName("fk_plz_postal_area");

                    b.Navigation("PostalArea");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.ApplicationUser", "User")
                        .WithMany("Visualizations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visualizations_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.VisualizationValue", b =>
                {
                    b.HasOne("PlzGeo.Api.Models.PostalArea", "PostalArea")
                        .WithMany("VisualizationValues")
                        .HasForeignKey("PostalAreaId")
                        .IsRequired()
                        .HasConstraintName("visualization_values_postal_area_id_fkey");

                    b.HasOne("PlzGeo.Api.Models.Visualization", "Visualization")
                        .WithMany("VisualizationValues")
                        .HasForeignKey("VisualizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("visualization_values_visualization_id_fkey");

                    b.Navigation("PostalArea");

                    b.Navigation("Visualization");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("Visualizations");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.PostalArea", b =>
                {
                    b.Navigation("Plz5Des");

                    b.Navigation("VisualizationValues");
                });

            modelBuilder.Entity("PlzGeo.Api.Models.Visualization", b =>
                {
                    b.Navigation("GroupLegendItems");

                    b.Navigation("HeatmapLegendItems");

                    b.Navigation("VisualizationValues");
                });
#pragma warning restore 612, 618
        }
    }
}
