services:

  postgis:
    image: postgis/postgis:17-3.5

    container_name: postgis

    environment:
      POSTGRES_DB: plzdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  backend:
      build:
        context: ./backend/PlzGeo.Api

      environment:
        Jwt__Key: ${JWT_KEY}

        ConnectionStrings__Postgis: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${POSTGRES_PASSWORD}

volumes:
  postgres_data: