services:

  postgis:
    image: postgis/postgis:17-3.5

    container_name: postgis

    environment:
      POSTGRES_DB: plzdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: danbandev99

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: